# Generated by Django 3.2.7 on 2021-09-02 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizza_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='pizza_topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Reg', 'Regular'), ('Sqr', 'Square')], max_length=7)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza_size')),
                ('toppings', models.ManyToManyField(blank=True, to='pizza.pizza_topping')),
            ],
        ),
    ]
