# Generated by Django 3.2.7 on 2021-09-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_pizza_toppings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='size',
            new_name='pizza_size',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='toppings',
            new_name='pizza_toppings',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pizza_size',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pizza_topping',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Square', 'Square')], default='Regular', max_length=7),
        ),
        migrations.AddField(
            model_name='pizza_size',
            name='pizza_size',
            field=models.CharField(default='Small', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='pizza_topping',
            name='topping',
            field=models.CharField(default='Onion', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_toppings',
            field=models.ManyToManyField(blank=True, to='pizza.Pizza_topping'),
        ),
    ]
