# Generated by Django 3.2.7 on 2021-09-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20210902_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_toppings',
            field=models.ManyToManyField(blank=True, to='pizza.Pizza_topping'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Square', 'Square')], max_length=7),
        ),
        migrations.AlterField(
            model_name='pizza_size',
            name='pizza_size',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pizza_topping',
            name='topping',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
